services:
  was:
    image: boot-was:latest
    container_name: boot-was-container
    restart: unless-stopped
    environment:
      - SERVER_PORT=8080
      - SERVER_SSL_ENABLED=false
    networks:
      - npm_shared_net
networks:
  npm_shared_net:
    name: npm-network
    external: true
